name: SimpleChat
version: 1.3
main: xyz.moeluoyu.simplechat.SimpleChat
author: moeluoyu
description: 自定义聊天格式
website: https://github.com/moeluoyu/SimpleChat
soft-depend: [PlaceholderAPI]

commands:
  simplechat:
    description: SimpleChat主命令
    usage: /simplechat reload
    aliases: [sc]
    permission: simplechat.admin

permissions:
  simplechat.admin:
    description: SimpleChat管理权限
    default: op